######################################
#
# BUSCO summary figure
# @version 4.0.0
# @since BUSCO 2.0.0
# 
# Copyright (c) 2016-2022, Evgeny Zdobnov (ez@ezlab.org)
# Licensed under the MIT license. See LICENSE.md file.
# Modified by Rodolfo Aramayo
# 2024-04-05
#
######################################

# Code modified from: https://vbaliga.github.io/posts/2019-04-28-verify-that-r-packages-are-installed-and-loaded/
# If a package is installed, it will be loaded.
# If any package are missing, the missing package(s) will be installed
# from CRAN and then loaded.
# First specify the packages of interest
## First specify the packages of interest
packages = c("Cairo", "ggplot2", "grid")

## Now load or install&load all
package.check <- lapply(packages, FUN = function(x) 
{if (!require(x, character.only = TRUE)) {install.packages(x, dependencies = TRUE);
library(x, character.only = TRUE)}})
# Load the required libraries
library(Cairo)
library(ggplot2)
library("grid")
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(tidyr))
suppressPackageStartupMessages(library(forcats))
suppressPackageStartupMessages(library(Cairo))

# !!! CONFIGURE YOUR PLOT HERE !!! 
# Output
my_file_type <- "png"
my_output <- paste("./","Busco_Plot_Figure.png", sep="/") 
my_width <- 20
my_height <- 15
my_unit <- "cm"

# Colors
my_colors <- c("#56B4E9", "#3492C7", "#F0E442", "#F04442")
# Bar height ratio
my_bar_height <- 0.75

# Legend
my_title <- "BUSCO Assessment Results"
my_subtitle <- "Eukaryotic Lineage"
# Font
my_family <- "sans"
my_size_ratio <- 1

# !!! SEE YOUR DATA HERE !!! 
# Your data as generated by python, remove or add more
my_species <- c('Ictalurus punctatus', 'Ictalurus punctatus', 'Ictalurus punctatus', 'Ictalurus punctatus', 'Ciona intestinalis', 'Ciona intestinalis', 'Ciona intestinalis', 'Ciona intestinalis', 'Chrysemys picta bellii', 'Chrysemys picta bellii', 'Chrysemys picta bellii', 'Chrysemys picta bellii', 'Canis lupus dingo', 'Canis lupus dingo', 'Canis lupus dingo', 'Canis lupus dingo', 'Vulpes vulpes', 'Vulpes vulpes', 'Vulpes vulpes', 'Vulpes vulpes', 'Fundulus heteroclitus', 'Fundulus heteroclitus', 'Fundulus heteroclitus', 'Fundulus heteroclitus', 'Nannospalax galili', 'Nannospalax galili', 'Nannospalax galili', 'Nannospalax galili', 'Moschus moschiferus', 'Moschus moschiferus', 'Moschus moschiferus', 'Moschus moschiferus', 'Amazona collaria', 'Amazona collaria', 'Amazona collaria', 'Amazona collaria', 'Canis lupus familiaris', 'Canis lupus familiaris', 'Canis lupus familiaris', 'Canis lupus familiaris', 'Parambassis ranga', 'Parambassis ranga', 'Parambassis ranga', 'Parambassis ranga', 'Homo sapiens', 'Homo sapiens', 'Homo sapiens', 'Homo sapiens')
#my_species <- factor(my_species)
#my_species <- factor(my_species, levels = levels(my_species)[c(length(levels(my_species)):1)])
# reorder your species here just by changing the values in the vector :
my_percentage <- c(62.0, 36.5, 0.8, 0.7, 81.2, 4.3, 7.1, 7.4, 63.9, 33.7, 2.4, -0.0, 63.1, 32.9, 1.6, 2.4, 56.5, 42.4, 0.4, 0.7, 61.6, 31.0, 5.1, 2.3, 68.2, 27.1, 3.1, 1.6, 65.1, 34.5, 0.0, 0.4, 62.7, 31.4, 3.1, 2.8, 47.5, 51.4, 0.8, 0.3, 44.3, 52.2, 0.8, 2.7, 35.7, 64.3, 0.0, 0.0)
my_values <- c(158, 93, 2, 2, 207, 11, 18, 19, 163, 86, 6, 0, 161, 84, 4, 6, 144, 108, 1, 2, 157, 79, 13, 6, 174, 69, 8, 4, 166, 88, 0, 1, 160, 80, 8, 7, 121, 131, 2, 1, 113, 133, 2, 7, 91, 164, 0, 0)

######################################
######################################
# Code to produce the graph
labsize = 1
if (length(my_species) > 10){
 labsize = 0.66
}
print("Plotting the figure ...")
category <- c(rep(c("S","D","F","M"),c(1)))
#category <- factor(category)
#category <- factor(category,levels(category)[c(4,1,2,3)])
df <- data.frame(my_species,my_percentage,my_values,category)
df <- df |>
  pivot_wider(
  id_cols = my_species,
  names_from = category,
  values_from = c(my_percentage, my_values)
  ) |>
  arrange(
    my_values_M,
    my_values_F,
    my_values_D,
    my_values_S
    ) |>
    pivot_longer(
      cols = !my_species,
      names_to = c(".value", "category"),
      names_pattern = "^(my_percentage|my_values)_([MFDS])$"
    ) |>
    mutate(my_species = factor(x = my_species, levels = rev(unique(my_species)))) |>
    mutate(category = factor(x = category, levels = c("S", "D", "F", "M")))
my_species <- df$my_species
my_values <- df$my_values
figure <- ggplot() + 
  
  geom_bar(aes(y = my_percentage, x = fct_rev(fct_inorder(my_species)), fill = category), position = position_stack(reverse = TRUE), data = df, stat="identity", width=my_bar_height) + 
  coord_flip() + 
  theme_gray(base_size = 8) + 
  scale_y_continuous(labels = c("0","20","40","60","80","100"), breaks = c(0,20,40,60,80,100)) + 
  scale_fill_manual(values = my_colors,labels =c(" Complete (C) and single-copy (S)  ",
                                                 " Complete (C) and duplicated (D)",
                                                 " Fragmented (F)  ",
                                                 " Missing (M)")) +   
  ggtitle(my_title, subtitle = my_subtitle) + 
  xlab("") + 
  ylab("\n%BUSCOs") + 

  theme(    plot.background = element_rect(fill='transparent', color = NA),    plot.title = element_text(family=my_family, hjust=0.5, colour = 'black', size = rel(2)*my_size_ratio, face = 'bold'),    plot.subtitle = element_text(family=my_family, hjust=0.5, colour = 'black', size = rel(1.45)*my_size_ratio, face = 'bold'),    legend.background = element_rect(fill='transparent', color = NA),    legend.box.background = element_rect(fill='transparent', color = NA),    legend.key = element_rect(fill = 'transparent', colour=NA),    legend.position = 'top',    legend.title = element_blank(),    legend.text = element_text(family=my_family, size = rel(1.05)*my_size_ratio),    panel.background = element_rect(fill='transparent', color = NA),    panel.grid.minor = element_blank(),    panel.grid.major = element_blank(),    axis.text.y = element_text(family=my_family, colour = 'black', size = rel(1.43)*my_size_ratio),    axis.text.x = element_text(family=my_family, colour = 'black', size = rel(1.43)*my_size_ratio),    axis.line = element_line(linewidth=0.78*my_size_ratio, colour = 'black'),    axis.ticks.length = unit(0.37, 'cm'),    axis.ticks.y = element_line(colour='white', linewidth = 0),    axis.ticks.x = element_line(colour='#222222', linewidth=0.5),    axis.title.x = element_text(family=my_family, colour = 'black', size=rel(1.1)*my_size_ratio, face = 'bold')  ) + 
  guides(fill = guide_legend(override.aes = list(colour = NULL))) +
  guides(fill=guide_legend(nrow=2,byrow=TRUE))
  
  for(i in rev(c(1:length(levels(my_species))))){
    detailed_values <- my_values[my_species==my_species[my_species==levels(my_species)[i]]]
    total_buscos <- sum(detailed_values)
    figure <- figure + 
    annotate("text", label=paste("C:", detailed_values[1] + detailed_values[2], " [S:", detailed_values[1], ", D:", detailed_values[2], "], F:", detailed_values[3], ", M:", detailed_values[4], ", n:", total_buscos, sep=""), 
             y=3, x = i, size = labsize*3.45*my_size_ratio, colour = "black", hjust=0, family=my_family)
  }
  
CairoFonts(
  regular = "sans:style=Regular",
  bold = "sans:style=Bold",
  italic = "sans:style=Italic"
)
Cairo(
  width = my_width,
  height = my_height,
  file = my_output,
  type = "png",
  dpi = 500,
  res = NA,
  units = my_unit,
  bg = "transparent"
)
grid.draw(figure)
dev.off()
print("Done")
